### ISSUE TITLE
关于孩子「逻辑」议题的头脑风暴

### ISSUE THREAD

**Issue by demongodYY** [TEDxChengdu/Kids#2]
请在之下随意回复，包括但不限于以下的讨论点：
- 与「逻辑」、「思辨」有关的话题
- 对于孩子这方面的教育、培养
- 相关的资料、教程
- 对「思辨」环境的思考
- 热门媒体，例如「奇葩说」等对孩子的影响
- 相关活动的策划想法
- 有相关的人物推荐
- 其他

**Comment by cathyray311** [comment]
有一个人想要推荐，知乎的一个心理学大V叫叶壮，因为之前有合作过几次，都是带领孩子玩游戏的主题。除了正确的引导教育，他在为孩子选择娱乐、游戏方式这方面很有一套，有特意在训练孩子这些方面的能力，又是很有意思的游戏内容。另外就是演讲风格风趣幽默，非常抓人。

**Comment by ClaireAut13** [comment]
说到媒体对孩子的影响倒是一下子就想到了芝麻街，国内应该也有类似的教育频道比如《少儿频道》之类的，寓教于乐，这些节目的本意是尽量让所有孩童都能受到相同的教育。

**Comment by demongodYY** [comment]
> 有一个人想要推荐，知乎的一个心理学大V叫叶壮，因为之前有合作过几次，都是带领孩子玩游戏的主题。除了正确的引导教育，他在为孩子选择娱乐、游戏方式这方面很有一套，有特意在训练孩子这些方面的能力，又是很有意思的游戏内容。另外就是演讲风格风趣幽默，非常抓人。

@cathyray311 网上有对应的视频吗？

**Comment by ghost** [comment]
关于对孩子逻辑思维能力的培养，我想到让孩子很小就开始学编程这件事。几个问题，为什么学习编程可以锻炼逻辑思维？将编程思维游戏化后教给孩子是否对他们锻炼逻辑/学习编程有实质帮助(比如TED-Ed前不久放出的Think Like A Coder系列短视频)？把很小的孩子送去学编程的家长很多是因为跟风或焦虑，从小学编程是否必要？如何缓解这种焦虑？

**Comment by demongodYY** [comment]
> 关于对孩子逻辑思维能力的培养，我想到让孩子很小就开始学编程这件事。几个问题，为什么学习编程可以锻炼逻辑思维？将编程思维游戏化后教给孩子是否对他们锻炼逻辑/学习编程有实质帮助(比如TED-Ed前不久放出的Think Like A Coder系列短视频)？把很小的孩子送去学编程的家长很多是因为跟风或焦虑，从小学编程是否必要？如何缓解这种焦虑？

@silashasalittledog 编程确实是很好的逻辑锻炼工具，也是很好的其他知识链接的粘合剂。我更愿意提少儿编程锻炼的是一种叫“信息素养”的东西。

关于要不要从小开始学编程的问题上，从我的建议是，家长最好自己能对相关的东西有一些了解，或者陪同孩子一起了解。要不然是无法解决焦虑的。

**Comment by demongodYY** [comment]
> 说到媒体对孩子的影响倒是一下子就想到了芝麻街，国内应该也有类似的教育频道比如《少儿频道》之类的，寓教于乐，这些节目的本意是尽量让所有孩童都能受到相同的教育。

感觉现在少儿频道都是重复放动画片居多，是我关注的太少了吗？

**Comment by BlairTan** [comment]
推荐一本书！《简单的逻辑学》by 【美国】D.Q 麦克伦尼

**Comment by BlairTan** [comment]
美国法学院的入学考试lsat里面有一项叫做“logical game”，以数列或者图像方式呈现。我在网上找了个链接--https://www.lsat-center.com/prep-guide/logic-games/  

logic game问题通常要求考生将变量放入序列或以不同的方式将变量其分组，并且考生通常使用草稿纸，通过画图得出答案。自1982年以来，Logic Game就一直是LSAT的一部分。

**Comment by BlairTan** [comment]
再推荐一个知乎答案“作者：知乎用户
链接：https://www.zhihu.com/question/27664757/answer/47796857
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

推荐普林斯顿评论Princeton Review Podcast 在美国是一个相当收欢迎的节目~有点像上海电视台1/7那样的探讨栏目一样。 节目在Itunes中的名字叫Logic in Everday Life, 是（LSAT）美国法学院入学考试的课外补充资料 这是podcast连接： http://www.radiopr.com/lsatpodcastfeed.xml听过一点，个人感觉这个节目对LSAT Logic Game有帮助【我暂时不打算考LSAT，听这个是为了练习听力】随手打开一个片段，我边听边写其中一段节目中的内容，你体会下Today on outside logic in everday life, we'll be discussing a subject I suspect as near and dear to the hearts of many podcast listeners. New York State Senator Carl Kruger is introducing a proposal banning the use IPODs, Blackberry cellular phones, and video games on NY streets. Spurred by what he describes as a nationawide problem of IPOD oblivion(state of unconsiciousness, forgetting things happening around), and setting recent death of his constituency(选民) who are hit by cars or buses are listening to IPODS, Kruger intends to slap a hundred dollar fine in the quarter appearance on pedestrains using these devices. Activists and legislators from mother states are looking to NY to see how this pans out as a testing ground for action in other cities. The proposal has met with outright rage opposition，objection )from NY city pedestrains, as well as tech-watchers from across the country. Even a website "IPOD http://Banned.Com" has sprung up overnight to follow the situation and marshall(enumerate) the effort agasint the ban. There's also been an explosion of commentaries on tech websites, such as "Slash Dot", a whole spectrum of (all kinds of... a wide range of...)reasons offered agasint the proposal. Some of these arguments are logical, some are a little less logical, some are outright funny.直接在iTUNES里订购即可

**Comment by BlairTan** [comment]
个人看法lsat这块太过硬核，可作为例子来讲解？或者衍生材料。做主要内容大可不必。

**Comment by BlairTan** [comment]
说到这里还想推荐一个和逻辑有关的动漫《虚构推理》。“绝大多数的推理、悬疑的动画片，它都有一个“解谜”的过程，侧重点可能不同，有的追求的是破案的过程，探案的过程，有的追求的是逻辑上的合理性，有的甚至会探讨人性……但是《虚构推理》，它的逻辑的点，侧重点，并不是破案，它的悬疑点，并没有设计在破案的过程上，而是反之，将案子的真相就早早揭示，或者说案子的真相对于这个故事来说，并不重要，反而是需要获得一个，令绝大多数人能信服的说法这一点，才变成了非常关键的逻辑的点，女主角需要用自己的智慧，来编一个，让整个案件成立的过程，来说服大众，所以，故事才会被称之为，“虚构推理”，因为推理的过程本身就是建立在不成立的过程中，简单说，缺乏关键证据，但是却没有逻辑上的出入，这是《虚构推理》的一大卖点。”

**Comment by BlairTan** [comment]
附上一个虚构推理的影评--https://baijiahao.baidu.com/s?id=1659795938493820313&wfr=spider&for=pc

内容--“但是抛开故事讲得不够好的地方，我觉得它阐述出的这种哲学性，我还是非常喜欢的。因为非常的写实。那就是，信息爆炸的社会，人们对于“真相”的追求已经越发浅显，“是非与黑白”的标准变得模糊，每个人心中已经获得了一个结论，所以你已经听不进别人的进言，“客观”对于很多人来说，也并不重要。这是一个事实，但我觉得，这世界，本该如此。虚构推理》告诉我们的，就是这么一个道理……如果一个人，获得了一个合理解释的过程和结果，那么他就很容易把这个事情当做事实和真相，如果这个结果被很多人认可，变成一个“公认”，那么客观就有可能被刷新；因为啊，“是非”也好，“黑白”也好，“道德”也好，都是没有标准的，都是主观的，都是相对的。
当绝大多数的人都认同一个“主观”的标准的时候，他就会看起来很像“客观”，而对于一些人来说，这个客观完全就可以成为一个标准，就像我说的，看动画认为现在的动画已经不是“手绘”的人，他们根本不在意动画是不是手绘的，只有我这种研究动画的人才会关系动画到底是怎么制作的，对于这些人来说，即便他们得出的结论是错误的，但也不会影响他们……所以称为他们的认知中的一种“客观”。

**Comment by BlairTan** [comment]
BBC纪录片《逻辑的乐趣 The Joy of Logic》

**Comment by BlairTan** [comment]
> BBC纪录片《逻辑的乐趣 The Joy of Logic》

https://pan.baidu.com/s/1Yr6E7qMnLZEX_F9LUpPi6w

**Comment by demongodYY** [comment]
> 个人看法lsat这块太过硬核，可作为例子来讲解？或者衍生材料。做主要内容大可不必。

是，还是要贴近生活

**Comment by demongodYY** [comment]
> 个人看法lsat这块太过硬核，可作为例子来讲解？或者衍生材料。做主要内容大可不必。

是，还是要贴近生活

> 说到这里还想推荐一个和逻辑有关的动漫《虚构推理》。“绝大多数的推理、悬疑的动画片，它都有一个“解谜”的过程，侧重点可能不同，有的追求的是破案的过程，探案的过程，有的追求的是逻辑上的合理性，有的甚至会探讨人性……但是《虚构推理》，它的逻辑的点，侧重点，并不是破案，它的悬疑点，并没有设计在破案的过程上，而是反之，将案子的真相就早早揭示，或者说案子的真相对于这个故事来说，并不重要，反而是需要获得一个，令绝大多数人能信服的说法这一点，才变成了非常关键的逻辑的点，女主角需要用自己的智慧，来编一个，让整个案件成立的过程，来说服大众，所以，故事才会被称之为，“虚构推理”，因为推理的过程本身就是建立在不成立的过程中，简单说，缺乏关键证据，但是却没有逻辑上的出入，这是《虚构推理》的一大卖点。”

推理好像是不错的一个点，我记得我小时候就喜欢看推理小说，侦探小说、还有柯南的漫画。不知道现在的小朋友们对于这方面的阅读？

**Comment by demongodYY** [comment]
> 说到这里还想推荐一个和逻辑有关的动漫《虚构推理》。“绝大多数的推理、悬疑的动画片，它都有一个“解谜”的过程，侧重点可能不同，有的追求的是破案的过程，探案的过程，有的追求的是逻辑上的合理性，有的甚至会探讨人性……但是《虚构推理》，它的逻辑的点，侧重点，并不是破案，它的悬疑点，并没有设计在破案的过程上，而是反之，将案子的真相就早早揭示，或者说案子的真相对于这个故事来说，并不重要，反而是需要获得一个，令绝大多数人能信服的说法这一点，才变成了非常关键的逻辑的点，女主角需要用自己的智慧，来编一个，让整个案件成立的过程，来说服大众，所以，故事才会被称之为，“虚构推理”，因为推理的过程本身就是建立在不成立的过程中，简单说，缺乏关键证据，但是却没有逻辑上的出入，这是《虚构推理》的一大卖点。”

推理好像是不错的一个点，我记得我小时候就喜欢看推理小说，侦探小说、还有柯南的漫画。不知道现在的小朋友们对于这方面的阅读？

**Comment by cathyray311** [comment]
> > 有一个人想要推荐，知乎的一个心理学大V叫叶壮，因为之前有合作过几次，都是带领孩子玩游戏的主题。除了正确的引导教育，他在为孩子选择娱乐、游戏方式这方面很有一套，有特意在训练孩子这些方面的能力，又是很有意思的游戏内容。另外就是演讲风格风趣幽默，非常抓人。
> 
> @cathyray311 网上有对应的视频吗？

https://mp.weixin.qq.com/s/piRnmo2P8e34xRfl8hfwQQ 这篇文的最下方就是视频  在41:50后是叶壮老师的讲授。

**Comment by SoCoPlus** [comment]
> 说到媒体对孩子的影响倒是一下子就想到了芝麻街，国内应该也有类似的教育频道比如《少儿频道》之类的，寓教于乐，这些节目的本意是尽量让所有孩童都能受到相同的教育。
